# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ahmettanakol/projects/moderndb/task-6-expressions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ahmettanakol/projects/moderndb/task-6-expressions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ahmettanakol/projects/moderndb/task-6-expressions/CMakeFiles /Users/ahmettanakol/projects/moderndb/task-6-expressions/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ahmettanakol/projects/moderndb/task-6-expressions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bm_expression

# Build rule for target.
bm_expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bm_expression
.PHONY : bm_expression

# fast build rule for target.
bm_expression/fast:
	$(MAKE) -f CMakeFiles/bm_expression.dir/build.make CMakeFiles/bm_expression.dir/build
.PHONY : bm_expression/fast

#=============================================================================
# Target rules for targets named lint_test

# Build rule for target.
lint_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint_test
.PHONY : lint_test

# fast build rule for target.
lint_test/fast:
	$(MAKE) -f CMakeFiles/lint_test.dir/build.make CMakeFiles/lint_test.dir/build
.PHONY : lint_test/fast

#=============================================================================
# Target rules for targets named moderndbs

# Build rule for target.
moderndbs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moderndbs
.PHONY : moderndbs

# fast build rule for target.
moderndbs/fast:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/build
.PHONY : moderndbs/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f CMakeFiles/googletest.dir/build.make CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

#=============================================================================
# Target rules for targets named gmock_src

# Build rule for target.
gmock_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_src
.PHONY : gmock_src

# fast build rule for target.
gmock_src/fast:
	$(MAKE) -f CMakeFiles/gmock_src.dir/build.make CMakeFiles/gmock_src.dir/build
.PHONY : gmock_src/fast

#=============================================================================
# Target rules for targets named gflags_src

# Build rule for target.
gflags_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gflags_src
.PHONY : gflags_src

# fast build rule for target.
gflags_src/fast:
	$(MAKE) -f CMakeFiles/gflags_src.dir/build.make CMakeFiles/gflags_src.dir/build
.PHONY : gflags_src/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named rapidjson_src

# Build rule for target.
rapidjson_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rapidjson_src
.PHONY : rapidjson_src

# fast build rule for target.
rapidjson_src/fast:
	$(MAKE) -f CMakeFiles/rapidjson_src.dir/build.make CMakeFiles/rapidjson_src.dir/build
.PHONY : rapidjson_src/fast

#=============================================================================
# Target rules for targets named gtest_src

# Build rule for target.
gtest_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_src
.PHONY : gtest_src

# fast build rule for target.
gtest_src/fast:
	$(MAKE) -f CMakeFiles/gtest_src.dir/build.make CMakeFiles/gtest_src.dir/build
.PHONY : gtest_src/fast

#=============================================================================
# Target rules for targets named lint

# Build rule for target.
lint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint
.PHONY : lint

# fast build rule for target.
lint/fast:
	$(MAKE) -f CMakeFiles/lint.dir/build.make CMakeFiles/lint.dir/build
.PHONY : lint/fast

#=============================================================================
# Target rules for targets named lint_tools

# Build rule for target.
lint_tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint_tools
.PHONY : lint_tools

# fast build rule for target.
lint_tools/fast:
	$(MAKE) -f CMakeFiles/lint_tools.dir/build.make CMakeFiles/lint_tools.dir/build
.PHONY : lint_tools/fast

#=============================================================================
# Target rules for targets named lint_src

# Build rule for target.
lint_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint_src
.PHONY : lint_src

# fast build rule for target.
lint_src/fast:
	$(MAKE) -f CMakeFiles/lint_src.dir/build.make CMakeFiles/lint_src.dir/build
.PHONY : lint_src/fast

#=============================================================================
# Target rules for targets named benchmark_src

# Build rule for target.
benchmark_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_src
.PHONY : benchmark_src

# fast build rule for target.
benchmark_src/fast:
	$(MAKE) -f CMakeFiles/benchmark_src.dir/build.make CMakeFiles/benchmark_src.dir/build
.PHONY : benchmark_src/fast

bench/bm_expression.o: bench/bm_expression.cc.o

.PHONY : bench/bm_expression.o

# target to build an object file
bench/bm_expression.cc.o:
	$(MAKE) -f CMakeFiles/bm_expression.dir/build.make CMakeFiles/bm_expression.dir/bench/bm_expression.cc.o
.PHONY : bench/bm_expression.cc.o

bench/bm_expression.i: bench/bm_expression.cc.i

.PHONY : bench/bm_expression.i

# target to preprocess a source file
bench/bm_expression.cc.i:
	$(MAKE) -f CMakeFiles/bm_expression.dir/build.make CMakeFiles/bm_expression.dir/bench/bm_expression.cc.i
.PHONY : bench/bm_expression.cc.i

bench/bm_expression.s: bench/bm_expression.cc.s

.PHONY : bench/bm_expression.s

# target to generate assembly for a file
bench/bm_expression.cc.s:
	$(MAKE) -f CMakeFiles/bm_expression.dir/build.make CMakeFiles/bm_expression.dir/bench/bm_expression.cc.s
.PHONY : bench/bm_expression.cc.s

src/codegen/example/printf.o: src/codegen/example/printf.cc.o

.PHONY : src/codegen/example/printf.o

# target to build an object file
src/codegen/example/printf.cc.o:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/example/printf.cc.o
.PHONY : src/codegen/example/printf.cc.o

src/codegen/example/printf.i: src/codegen/example/printf.cc.i

.PHONY : src/codegen/example/printf.i

# target to preprocess a source file
src/codegen/example/printf.cc.i:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/example/printf.cc.i
.PHONY : src/codegen/example/printf.cc.i

src/codegen/example/printf.s: src/codegen/example/printf.cc.s

.PHONY : src/codegen/example/printf.s

# target to generate assembly for a file
src/codegen/example/printf.cc.s:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/example/printf.cc.s
.PHONY : src/codegen/example/printf.cc.s

src/codegen/expression.o: src/codegen/expression.cc.o

.PHONY : src/codegen/expression.o

# target to build an object file
src/codegen/expression.cc.o:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/expression.cc.o
.PHONY : src/codegen/expression.cc.o

src/codegen/expression.i: src/codegen/expression.cc.i

.PHONY : src/codegen/expression.i

# target to preprocess a source file
src/codegen/expression.cc.i:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/expression.cc.i
.PHONY : src/codegen/expression.cc.i

src/codegen/expression.s: src/codegen/expression.cc.s

.PHONY : src/codegen/expression.s

# target to generate assembly for a file
src/codegen/expression.cc.s:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/expression.cc.s
.PHONY : src/codegen/expression.cc.s

src/codegen/jit.o: src/codegen/jit.cc.o

.PHONY : src/codegen/jit.o

# target to build an object file
src/codegen/jit.cc.o:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/jit.cc.o
.PHONY : src/codegen/jit.cc.o

src/codegen/jit.i: src/codegen/jit.cc.i

.PHONY : src/codegen/jit.i

# target to preprocess a source file
src/codegen/jit.cc.i:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/jit.cc.i
.PHONY : src/codegen/jit.cc.i

src/codegen/jit.s: src/codegen/jit.cc.s

.PHONY : src/codegen/jit.s

# target to generate assembly for a file
src/codegen/jit.cc.s:
	$(MAKE) -f CMakeFiles/moderndbs.dir/build.make CMakeFiles/moderndbs.dir/src/codegen/jit.cc.s
.PHONY : src/codegen/jit.cc.s

test/expression_test.o: test/expression_test.cc.o

.PHONY : test/expression_test.o

# target to build an object file
test/expression_test.cc.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/expression_test.cc.o
.PHONY : test/expression_test.cc.o

test/expression_test.i: test/expression_test.cc.i

.PHONY : test/expression_test.i

# target to preprocess a source file
test/expression_test.cc.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/expression_test.cc.i
.PHONY : test/expression_test.cc.i

test/expression_test.s: test/expression_test.cc.s

.PHONY : test/expression_test.s

# target to generate assembly for a file
test/expression_test.cc.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/expression_test.cc.s
.PHONY : test/expression_test.cc.s

test/tester.o: test/tester.cc.o

.PHONY : test/tester.o

# target to build an object file
test/tester.cc.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.cc.o
.PHONY : test/tester.cc.o

test/tester.i: test/tester.cc.i

.PHONY : test/tester.i

# target to preprocess a source file
test/tester.cc.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.cc.i
.PHONY : test/tester.cc.i

test/tester.s: test/tester.cc.s

.PHONY : test/tester.s

# target to generate assembly for a file
test/tester.cc.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.cc.s
.PHONY : test/tester.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bm_expression"
	@echo "... lint_test"
	@echo "... moderndbs"
	@echo "... tester"
	@echo "... googletest"
	@echo "... gmock_src"
	@echo "... gflags_src"
	@echo "... intrinsics_gen"
	@echo "... rapidjson_src"
	@echo "... gtest_src"
	@echo "... lint"
	@echo "... lint_tools"
	@echo "... test"
	@echo "... lint_src"
	@echo "... benchmark_src"
	@echo "... bench/bm_expression.o"
	@echo "... bench/bm_expression.i"
	@echo "... bench/bm_expression.s"
	@echo "... src/codegen/example/printf.o"
	@echo "... src/codegen/example/printf.i"
	@echo "... src/codegen/example/printf.s"
	@echo "... src/codegen/expression.o"
	@echo "... src/codegen/expression.i"
	@echo "... src/codegen/expression.s"
	@echo "... src/codegen/jit.o"
	@echo "... src/codegen/jit.i"
	@echo "... src/codegen/jit.s"
	@echo "... test/expression_test.o"
	@echo "... test/expression_test.i"
	@echo "... test/expression_test.s"
	@echo "... test/tester.o"
	@echo "... test/tester.i"
	@echo "... test/tester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

